/** @type {import('@remix-run/dev').AppConfig} */
export default {
  ignoredRouteFiles: ["**/.*"],
  serverModuleFormat: "esm",
  serverPlatform: "node",
  serverBuildTarget: "vercel",
  server: "./app/entry.vercel.tsx",
  serverDependenciesToBundle: [
    /^@remix-run\/.*/,
    /^remix-.*/,
    /^@webcontainer\/.*/,
    /^@xterm\/.*/,
    /^@codemirror\/.*/,
    /^@lezer\/.*/,
    /^@uiw\/.*/,
    /^@nanostores\/.*/,
    /^nanostores/,
    /^@ai-sdk\/.*/,
    /^ai$/,
    /^@modelcontextprotocol\/.*/,
    /^@octokit\/.*/,
    /^@openrouter\/.*/,
    /^@phosphor-icons\/.*/,
    /^@radix-ui\/.*/,
    /^@headlessui\/.*/,
    /^@heroicons\/.*/,
    /^@iconify-json\/.*/,
    /^@iconify\/.*/,
    /^@tanstack\/.*/,
    /^@unocss\/.*/,
    /^unocss/,
    /^@unocss\/reset/,
    /^class-variance-authority/,
    /^clsx/,
    /^tailwind-merge/,
    /^lucide-react/,
    /^react-icons/,
    /^react-hotkeys-hook/,
    /^react-markdown/,
    /^react-qrcode-logo/,
    /^react-resizable-panels/,
    /^react-toastify/,
    /^react-window/,
    /^react-beautiful-dnd/,
    /^react-dnd/,
    /^react-dnd-html5-backend/,
    /^react-chartjs-2/,
    /^chart\.js/,
    /^framer-motion/,
    /^date-fns/,
    /^diff/,
    /^dotenv/,
    /^file-saver/,
    /^ignore/,
    /^isomorphic-git/,
    /^istextorbinary/,
    /^jose/,
    /^js-cookie/,
    /^jspdf/,
    /^jszip/,
    /^mime/,
    /^ollama-ai-provider/,
    /^path-browserify/,
    /^rehype-raw/,
    /^rehype-sanitize/,
    /^remark-gfm/,
    /^rollup-plugin-node-polyfills/,
    /^shiki/,
    /^unist-util-visit/,
    /^use-debounce/,
    /^vite-plugin-node-polyfills/,
    /^zod/,
    /^zustand/,
    /^chalk/,
    /^crypto-browserify/,
    /^stream-browserify/,
    /^node-fetch/,
  ],
};
